#ifndef OPENGLES_2_DECLARATION
#define OPENGLES_2_DECLARATION

#define GL_GLEXT_PROTOTYPES 1

#ifndef FORCE_FULL_OPENGL_2
#include <SDL2/SDL_opengles2.h>
#define GLES2_SDL_GL_CONTEXT_SETTING SDL_GL_CONTEXT_PROFILE_ES
#else
#include <SDL2/SDL_opengl.h>
#define GLES2_SDL_GL_CONTEXT_SETTING SDL_GL_CONTEXT_PROFILE_CORE
#endif

#endif
